{% set name = "pyarrow-stubs" %}
{% set version = "20.0.0.20251104" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyarrow_stubs-{{ version }}.tar.gz
  sha256: a08964a67627c28354668af64d7021fb8d51fd69322ddb8b7a9c0336e49a367b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0

test:
  commands:
    - pip check
    - test -f $SP_DIR/pyarrow-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\pyarrow-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip
    # workaround for pip check needing pyarrow as a dependency
    - pyarrow >=17
    - python {{ python_min }}

about:
  summary: Type annotations for pyarrow
  license: BSD-2-Clause
  license_file: LICENSE
  home: https://github.com/zen-xu/pyarrow-stubs

extra:
  recipe-maintainers:
    - mariusvniekerk
