{% set name = "pyarrow-stubs" %}
{% set version = "19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyarrow_stubs-{{ version }}.tar.gz
  sha256: e91c9b8b3bc551d53716bb466b02967d93b9827b1adc3d36bb4bba8662a81ccd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0

test:
  commands:
    - pip check
    - test -f $SP_DIR/pyarrow-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\pyarrow-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip
    # workaround for pip check needing pyarrow as a dependency
    - pyarrow >=17
    - python {{ python_min }}

about:
  summary: Type annotations for pyarrow
  license: BSD-2-Clause
  license_file: LICENSE
  home: https://github.com/zen-xu/pyarrow-stubs

extra:
  recipe-maintainers:
    - mariusvniekerk
