{% set name = "pyarrow-stubs" %}
{% set version = "17.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyarrow_stubs-{{ version }}.tar.gz
  sha256: d0a7b3f661ebddf53291df959648c84d109055aa48b245686f1f1878c249a2b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - hatchling
    - pip
  run:
    - python >=3.8,<4.0

test:
  commands:
    - pip check
    - test -f $SP_DIR/pyarrow-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\pyarrow-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip
    # workaround for pip check needing pyarrow as a dependency
    - pyarrow >=17

about:
  summary: Type annotations for pyarrow
  license: BSD-2-Clause
  license_file: LICENSE
  home: https://github.com/zen-xu/pyarrow-stubs

extra:
  recipe-maintainers:
    - mariusvniekerk
