{% set name = "pyarrow-stubs" %}
{% set version = "17.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyarrow_stubs-{{ version }}.tar.gz
  sha256: 6c124339acae4f81c59a9e55acc9a90cf5ddb3694ad4fb498a053fedf152097d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8,<4.0
    - hatchling
    - pip
  run:
    - python >=3.8,<4.0

test:
  commands:
    - pip check
    - test -f $SP_DIR/pyarrow-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\pyarrow-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip
    # workaround for pip check needing pyarrow as a dependency
    - pyarrow >=17

about:
  summary: Type annotations for pyarrow
  license: BSD-2-Clause
  license_file: LICENSE
  home: https://github.com/zen-xu/pyarrow-stubs

extra:
  recipe-maintainers:
    - mariusvniekerk
